### ISSUE TITLE
Can we change the color of the graphs to Blue?

### ISSUE THREAD

**Issue by jeonbik** [sanjelarun/QML_Review_chat_generator#1]
Just trying to follow the standard approach 🙂. I might create a PR for this issue later.

**Comment by sanjelarun** [comment]
Issue is fixed. Can you please verify the color? Also, if you have a particular hexCode , let me know.

**Comment by jeonbik** [comment]
* Can we go with the list blue color? I think the hex code is: #ADD8E6
* Also, Let's combine: 1. ArXiv and arXiv pre-print in top_publishers.png.
* There is no publisher for top publisher in `top_publishers.png` figure. Can we make sure we get the correct corresponding publisher.
* Can you please remove the year 2024 in `publications_by_year.png` image.

**Comment by sanjelarun** [comment]
- Can we go with the list blue color? I think the hex code is: #ADD8E6 -> Done
- Also, Let's combine: 1. ArXiv and arXiv pre-print in top_publishers.png. -> Merge these labels as arXiv.
- There is no publisher for top publisher in top_publishers.png figure. Can we make sure we get the correct corresponding publisher. - Added new tick label as missing publisher. 

Let me know if you any other changes
 

Can you please remove the year 2024 in publications_by_year.png image.

**Comment by jeonbik** [comment]
I think this problem is solved for now. I am closing this issue. However, I have made some changes to the figure that I will update later.
